//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AdminModel", "FK_tb_GroupMapping_tb_UserGroups", "tb_UserGroups", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CSI.Business.DataObjects.tb_UserGroups), "tb_GroupMapping", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CSI.Business.DataObjects.tb_GroupMapping), true)]

#endregion

namespace CSI.Business.DataObjects
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AdminModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AdminModelContainer object using the connection string found in the 'AdminModelContainer' section of the application configuration file.
        /// </summary>
        public AdminModelContainer() : base("name=AdminModelContainer", "AdminModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AdminModelContainer object.
        /// </summary>
        public AdminModelContainer(string connectionString) : base(connectionString, "AdminModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AdminModelContainer object.
        /// </summary>
        public AdminModelContainer(EntityConnection connection) : base(connection, "AdminModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_GroupMapping> tb_GroupMapping
        {
            get
            {
                if ((_tb_GroupMapping == null))
                {
                    _tb_GroupMapping = base.CreateObjectSet<tb_GroupMapping>("tb_GroupMapping");
                }
                return _tb_GroupMapping;
            }
        }
        private ObjectSet<tb_GroupMapping> _tb_GroupMapping;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_SecurityMatch> tb_SecurityMatch
        {
            get
            {
                if ((_tb_SecurityMatch == null))
                {
                    _tb_SecurityMatch = base.CreateObjectSet<tb_SecurityMatch>("tb_SecurityMatch");
                }
                return _tb_SecurityMatch;
            }
        }
        private ObjectSet<tb_SecurityMatch> _tb_SecurityMatch;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_UserGroups> tb_UserGroups
        {
            get
            {
                if ((_tb_UserGroups == null))
                {
                    _tb_UserGroups = base.CreateObjectSet<tb_UserGroups>("tb_UserGroups");
                }
                return _tb_UserGroups;
            }
        }
        private ObjectSet<tb_UserGroups> _tb_UserGroups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_User> tb_User
        {
            get
            {
                if ((_tb_User == null))
                {
                    _tb_User = base.CreateObjectSet<tb_User>("tb_User");
                }
                return _tb_User;
            }
        }
        private ObjectSet<tb_User> _tb_User;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_ScreensControl> tb_ScreensControl
        {
            get
            {
                if ((_tb_ScreensControl == null))
                {
                    _tb_ScreensControl = base.CreateObjectSet<tb_ScreensControl>("tb_ScreensControl");
                }
                return _tb_ScreensControl;
            }
        }
        private ObjectSet<tb_ScreensControl> _tb_ScreensControl;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_GroupMapping EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_GroupMapping(tb_GroupMapping tb_GroupMapping)
        {
            base.AddObject("tb_GroupMapping", tb_GroupMapping);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_SecurityMatch EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_SecurityMatch(tb_SecurityMatch tb_SecurityMatch)
        {
            base.AddObject("tb_SecurityMatch", tb_SecurityMatch);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_UserGroups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_UserGroups(tb_UserGroups tb_UserGroups)
        {
            base.AddObject("tb_UserGroups", tb_UserGroups);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_User(tb_User tb_User)
        {
            base.AddObject("tb_User", tb_User);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_ScreensControl EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_ScreensControl(tb_ScreensControl tb_ScreensControl)
        {
            base.AddObject("tb_ScreensControl", tb_ScreensControl);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="groupID">No Metadata Documentation available.</param>
        public ObjectResult<sp_ADM020_LoadGroup_Result> sp_ADM020_LoadGroup(Nullable<global::System.Decimal> groupID)
        {
            ObjectParameter groupIDParameter;
            if (groupID.HasValue)
            {
                groupIDParameter = new ObjectParameter("GroupID", groupID);
            }
            else
            {
                groupIDParameter = new ObjectParameter("GroupID", typeof(global::System.Decimal));
            }
    
            return base.ExecuteFunction<sp_ADM020_LoadGroup_Result>("sp_ADM020_LoadGroup", groupIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="groupID">No Metadata Documentation available.</param>
        public ObjectResult<sp_ADM020_LoadUserByGroup_Result> sp_ADM020_LoadUserByGroup(Nullable<global::System.Decimal> groupID)
        {
            ObjectParameter groupIDParameter;
            if (groupID.HasValue)
            {
                groupIDParameter = new ObjectParameter("GroupID", groupID);
            }
            else
            {
                groupIDParameter = new ObjectParameter("GroupID", typeof(global::System.Decimal));
            }
    
            return base.ExecuteFunction<sp_ADM020_LoadUserByGroup_Result>("sp_ADM020_LoadUserByGroup", groupIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<sp_ADM010_UserMaintenance_SearchAll_Result> sp_ADM010_UserMaintenance_SearchAll()
        {
            return base.ExecuteFunction<sp_ADM010_UserMaintenance_SearchAll_Result>("sp_ADM010_UserMaintenance_SearchAll");
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AdminModel", Name="tb_GroupMapping")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_GroupMapping : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_GroupMapping object.
        /// </summary>
        /// <param name="uSERID">Initial value of the USERID property.</param>
        /// <param name="gROUPID">Initial value of the GROUPID property.</param>
        public static tb_GroupMapping Createtb_GroupMapping(global::System.String uSERID, global::System.Decimal gROUPID)
        {
            tb_GroupMapping tb_GroupMapping = new tb_GroupMapping();
            tb_GroupMapping.USERID = uSERID;
            tb_GroupMapping.GROUPID = gROUPID;
            return tb_GroupMapping;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USERID
        {
            get
            {
                return _USERID;
            }
            set
            {
                if (_USERID != value)
                {
                    OnUSERIDChanging(value);
                    ReportPropertyChanging("USERID");
                    _USERID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("USERID");
                    OnUSERIDChanged();
                }
            }
        }
        private global::System.String _USERID;
        partial void OnUSERIDChanging(global::System.String value);
        partial void OnUSERIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal GROUPID
        {
            get
            {
                return _GROUPID;
            }
            set
            {
                if (_GROUPID != value)
                {
                    OnGROUPIDChanging(value);
                    ReportPropertyChanging("GROUPID");
                    _GROUPID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GROUPID");
                    OnGROUPIDChanged();
                }
            }
        }
        private global::System.Decimal _GROUPID;
        partial void OnGROUPIDChanging(global::System.Decimal value);
        partial void OnGROUPIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AdminModel", "FK_tb_GroupMapping_tb_UserGroups", "tb_UserGroups")]
        public tb_UserGroups tb_UserGroups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_UserGroups>("AdminModel.FK_tb_GroupMapping_tb_UserGroups", "tb_UserGroups").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_UserGroups>("AdminModel.FK_tb_GroupMapping_tb_UserGroups", "tb_UserGroups").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_UserGroups> tb_UserGroupsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_UserGroups>("AdminModel.FK_tb_GroupMapping_tb_UserGroups", "tb_UserGroups");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_UserGroups>("AdminModel.FK_tb_GroupMapping_tb_UserGroups", "tb_UserGroups", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AdminModel", Name="tb_ScreensControl")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_ScreensControl : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_ScreensControl object.
        /// </summary>
        /// <param name="screenID">Initial value of the ScreenID property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="iPaddress">Initial value of the IPaddress property.</param>
        public static tb_ScreensControl Createtb_ScreensControl(global::System.String screenID, global::System.String userID, global::System.String iPaddress)
        {
            tb_ScreensControl tb_ScreensControl = new tb_ScreensControl();
            tb_ScreensControl.ScreenID = screenID;
            tb_ScreensControl.UserID = userID;
            tb_ScreensControl.IPaddress = iPaddress;
            return tb_ScreensControl;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ScreenID
        {
            get
            {
                return _ScreenID;
            }
            set
            {
                if (_ScreenID != value)
                {
                    OnScreenIDChanging(value);
                    ReportPropertyChanging("ScreenID");
                    _ScreenID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ScreenID");
                    OnScreenIDChanged();
                }
            }
        }
        private global::System.String _ScreenID;
        partial void OnScreenIDChanging(global::System.String value);
        partial void OnScreenIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.String _UserID;
        partial void OnUserIDChanging(global::System.String value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IPaddress
        {
            get
            {
                return _IPaddress;
            }
            set
            {
                if (_IPaddress != value)
                {
                    OnIPaddressChanging(value);
                    ReportPropertyChanging("IPaddress");
                    _IPaddress = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IPaddress");
                    OnIPaddressChanged();
                }
            }
        }
        private global::System.String _IPaddress;
        partial void OnIPaddressChanging(global::System.String value);
        partial void OnIPaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastResponse
        {
            get
            {
                return _LastResponse;
            }
            set
            {
                OnLastResponseChanging(value);
                ReportPropertyChanging("LastResponse");
                _LastResponse = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastResponse");
                OnLastResponseChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastResponse;
        partial void OnLastResponseChanging(Nullable<global::System.DateTime> value);
        partial void OnLastResponseChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AdminModel", Name="tb_SecurityMatch")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_SecurityMatch : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_SecurityMatch object.
        /// </summary>
        /// <param name="sECURITYID">Initial value of the SECURITYID property.</param>
        /// <param name="cREATEDATE">Initial value of the CREATEDATE property.</param>
        /// <param name="cREATEUSER">Initial value of the CREATEUSER property.</param>
        public static tb_SecurityMatch Createtb_SecurityMatch(global::System.Decimal sECURITYID, global::System.DateTime cREATEDATE, global::System.String cREATEUSER)
        {
            tb_SecurityMatch tb_SecurityMatch = new tb_SecurityMatch();
            tb_SecurityMatch.SECURITYID = sECURITYID;
            tb_SecurityMatch.CREATEDATE = cREATEDATE;
            tb_SecurityMatch.CREATEUSER = cREATEUSER;
            return tb_SecurityMatch;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SECURITYID
        {
            get
            {
                return _SECURITYID;
            }
            set
            {
                if (_SECURITYID != value)
                {
                    OnSECURITYIDChanging(value);
                    ReportPropertyChanging("SECURITYID");
                    _SECURITYID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SECURITYID");
                    OnSECURITYIDChanged();
                }
            }
        }
        private global::System.Decimal _SECURITYID;
        partial void OnSECURITYIDChanging(global::System.Decimal value);
        partial void OnSECURITYIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USERID
        {
            get
            {
                return _USERID;
            }
            set
            {
                OnUSERIDChanging(value);
                ReportPropertyChanging("USERID");
                _USERID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USERID");
                OnUSERIDChanged();
            }
        }
        private global::System.String _USERID;
        partial void OnUSERIDChanging(global::System.String value);
        partial void OnUSERIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> GROUPID
        {
            get
            {
                return _GROUPID;
            }
            set
            {
                OnGROUPIDChanging(value);
                ReportPropertyChanging("GROUPID");
                _GROUPID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GROUPID");
                OnGROUPIDChanged();
            }
        }
        private Nullable<global::System.Decimal> _GROUPID;
        partial void OnGROUPIDChanging(Nullable<global::System.Decimal> value);
        partial void OnGROUPIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SCREENID
        {
            get
            {
                return _SCREENID;
            }
            set
            {
                OnSCREENIDChanging(value);
                ReportPropertyChanging("SCREENID");
                _SCREENID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SCREENID");
                OnSCREENIDChanged();
            }
        }
        private Nullable<global::System.Decimal> _SCREENID;
        partial void OnSCREENIDChanging(Nullable<global::System.Decimal> value);
        partial void OnSCREENIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PERMISSION
        {
            get
            {
                return _PERMISSION;
            }
            set
            {
                OnPERMISSIONChanging(value);
                ReportPropertyChanging("PERMISSION");
                _PERMISSION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PERMISSION");
                OnPERMISSIONChanged();
            }
        }
        private global::System.String _PERMISSION;
        partial void OnPERMISSIONChanging(global::System.String value);
        partial void OnPERMISSIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CREATEDATE
        {
            get
            {
                return _CREATEDATE;
            }
            set
            {
                OnCREATEDATEChanging(value);
                ReportPropertyChanging("CREATEDATE");
                _CREATEDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATEDATE");
                OnCREATEDATEChanged();
            }
        }
        private global::System.DateTime _CREATEDATE;
        partial void OnCREATEDATEChanging(global::System.DateTime value);
        partial void OnCREATEDATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UPDATEDATE
        {
            get
            {
                return _UPDATEDATE;
            }
            set
            {
                OnUPDATEDATEChanging(value);
                ReportPropertyChanging("UPDATEDATE");
                _UPDATEDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATEDATE");
                OnUPDATEDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _UPDATEDATE;
        partial void OnUPDATEDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnUPDATEDATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CREATEUSER
        {
            get
            {
                return _CREATEUSER;
            }
            set
            {
                OnCREATEUSERChanging(value);
                ReportPropertyChanging("CREATEUSER");
                _CREATEUSER = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CREATEUSER");
                OnCREATEUSERChanged();
            }
        }
        private global::System.String _CREATEUSER;
        partial void OnCREATEUSERChanging(global::System.String value);
        partial void OnCREATEUSERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UPDATEUSER
        {
            get
            {
                return _UPDATEUSER;
            }
            set
            {
                OnUPDATEUSERChanging(value);
                ReportPropertyChanging("UPDATEUSER");
                _UPDATEUSER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UPDATEUSER");
                OnUPDATEUSERChanged();
            }
        }
        private global::System.String _UPDATEUSER;
        partial void OnUPDATEUSERChanging(global::System.String value);
        partial void OnUPDATEUSERChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AdminModel", Name="tb_User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_User object.
        /// </summary>
        /// <param name="runningID">Initial value of the RunningID property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        /// <param name="createUser">Initial value of the CreateUser property.</param>
        public static tb_User Createtb_User(global::System.Int32 runningID, global::System.String userID, global::System.String firstName, global::System.String password, global::System.DateTime createDate, global::System.String createUser)
        {
            tb_User tb_User = new tb_User();
            tb_User.RunningID = runningID;
            tb_User.UserID = userID;
            tb_User.FirstName = firstName;
            tb_User.Password = password;
            tb_User.CreateDate = createDate;
            tb_User.CreateUser = createUser;
            return tb_User;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RunningID
        {
            get
            {
                return _RunningID;
            }
            set
            {
                OnRunningIDChanging(value);
                ReportPropertyChanging("RunningID");
                _RunningID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RunningID");
                OnRunningIDChanged();
            }
        }
        private global::System.Int32 _RunningID;
        partial void OnRunningIDChanging(global::System.Int32 value);
        partial void OnRunningIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.String _UserID;
        partial void OnUserIDChanging(global::System.String value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tel
        {
            get
            {
                return _Tel;
            }
            set
            {
                OnTelChanging(value);
                ReportPropertyChanging("Tel");
                _Tel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tel");
                OnTelChanged();
            }
        }
        private global::System.String _Tel;
        partial void OnTelChanging(global::System.String value);
        partial void OnTelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mobile
        {
            get
            {
                return _Mobile;
            }
            set
            {
                OnMobileChanging(value);
                ReportPropertyChanging("Mobile");
                _Mobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mobile");
                OnMobileChanged();
            }
        }
        private global::System.String _Mobile;
        partial void OnMobileChanging(global::System.String value);
        partial void OnMobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> WarehouseID
        {
            get
            {
                return _WarehouseID;
            }
            set
            {
                OnWarehouseIDChanging(value);
                ReportPropertyChanging("WarehouseID");
                _WarehouseID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WarehouseID");
                OnWarehouseIDChanged();
            }
        }
        private Nullable<global::System.Int32> _WarehouseID;
        partial void OnWarehouseIDChanging(Nullable<global::System.Int32> value);
        partial void OnWarehouseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OwnerID
        {
            get
            {
                return _OwnerID;
            }
            set
            {
                OnOwnerIDChanging(value);
                ReportPropertyChanging("OwnerID");
                _OwnerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OwnerID");
                OnOwnerIDChanged();
            }
        }
        private Nullable<global::System.Int32> _OwnerID;
        partial void OnOwnerIDChanging(Nullable<global::System.Int32> value);
        partial void OnOwnerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreateUser
        {
            get
            {
                return _CreateUser;
            }
            set
            {
                OnCreateUserChanging(value);
                ReportPropertyChanging("CreateUser");
                _CreateUser = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreateUser");
                OnCreateUserChanged();
            }
        }
        private global::System.String _CreateUser;
        partial void OnCreateUserChanging(global::System.String value);
        partial void OnCreateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdateUser
        {
            get
            {
                return _UpdateUser;
            }
            set
            {
                OnUpdateUserChanging(value);
                ReportPropertyChanging("UpdateUser");
                _UpdateUser = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdateUser");
                OnUpdateUserChanged();
            }
        }
        private global::System.String _UpdateUser;
        partial void OnUpdateUserChanging(global::System.String value);
        partial void OnUpdateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateDate
        {
            get
            {
                return _UpdateDate;
            }
            set
            {
                OnUpdateDateChanging(value);
                ReportPropertyChanging("UpdateDate");
                _UpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateDate");
                OnUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateDate;
        partial void OnUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LoginType
        {
            get
            {
                return _LoginType;
            }
            set
            {
                OnLoginTypeChanging(value);
                ReportPropertyChanging("LoginType");
                _LoginType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoginType");
                OnLoginTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _LoginType;
        partial void OnLoginTypeChanging(Nullable<global::System.Int32> value);
        partial void OnLoginTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DomainIPAddress
        {
            get
            {
                return _DomainIPAddress;
            }
            set
            {
                OnDomainIPAddressChanging(value);
                ReportPropertyChanging("DomainIPAddress");
                _DomainIPAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DomainIPAddress");
                OnDomainIPAddressChanged();
            }
        }
        private global::System.String _DomainIPAddress;
        partial void OnDomainIPAddressChanging(global::System.String value);
        partial void OnDomainIPAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DomainName
        {
            get
            {
                return _DomainName;
            }
            set
            {
                OnDomainNameChanging(value);
                ReportPropertyChanging("DomainName");
                _DomainName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DomainName");
                OnDomainNameChanged();
            }
        }
        private global::System.String _DomainName;
        partial void OnDomainNameChanging(global::System.String value);
        partial void OnDomainNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OwnerIDWeb
        {
            get
            {
                return _OwnerIDWeb;
            }
            set
            {
                OnOwnerIDWebChanging(value);
                ReportPropertyChanging("OwnerIDWeb");
                _OwnerIDWeb = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OwnerIDWeb");
                OnOwnerIDWebChanged();
            }
        }
        private Nullable<global::System.Int32> _OwnerIDWeb;
        partial void OnOwnerIDWebChanging(Nullable<global::System.Int32> value);
        partial void OnOwnerIDWebChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AdminModel", Name="tb_UserGroups")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_UserGroups : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_UserGroups object.
        /// </summary>
        /// <param name="gROUPID">Initial value of the GROUPID property.</param>
        /// <param name="cREATEDATE">Initial value of the CREATEDATE property.</param>
        /// <param name="cREATEUSER">Initial value of the CREATEUSER property.</param>
        public static tb_UserGroups Createtb_UserGroups(global::System.Decimal gROUPID, global::System.DateTime cREATEDATE, global::System.String cREATEUSER)
        {
            tb_UserGroups tb_UserGroups = new tb_UserGroups();
            tb_UserGroups.GROUPID = gROUPID;
            tb_UserGroups.CREATEDATE = cREATEDATE;
            tb_UserGroups.CREATEUSER = cREATEUSER;
            return tb_UserGroups;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal GROUPID
        {
            get
            {
                return _GROUPID;
            }
            set
            {
                if (_GROUPID != value)
                {
                    OnGROUPIDChanging(value);
                    ReportPropertyChanging("GROUPID");
                    _GROUPID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GROUPID");
                    OnGROUPIDChanged();
                }
            }
        }
        private global::System.Decimal _GROUPID;
        partial void OnGROUPIDChanging(global::System.Decimal value);
        partial void OnGROUPIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GROUPNAME
        {
            get
            {
                return _GROUPNAME;
            }
            set
            {
                OnGROUPNAMEChanging(value);
                ReportPropertyChanging("GROUPNAME");
                _GROUPNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GROUPNAME");
                OnGROUPNAMEChanged();
            }
        }
        private global::System.String _GROUPNAME;
        partial void OnGROUPNAMEChanging(global::System.String value);
        partial void OnGROUPNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPTION
        {
            get
            {
                return _DESCRIPTION;
            }
            set
            {
                OnDESCRIPTIONChanging(value);
                ReportPropertyChanging("DESCRIPTION");
                _DESCRIPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIPTION");
                OnDESCRIPTIONChanged();
            }
        }
        private global::System.String _DESCRIPTION;
        partial void OnDESCRIPTIONChanging(global::System.String value);
        partial void OnDESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CREATEDATE
        {
            get
            {
                return _CREATEDATE;
            }
            set
            {
                OnCREATEDATEChanging(value);
                ReportPropertyChanging("CREATEDATE");
                _CREATEDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATEDATE");
                OnCREATEDATEChanged();
            }
        }
        private global::System.DateTime _CREATEDATE;
        partial void OnCREATEDATEChanging(global::System.DateTime value);
        partial void OnCREATEDATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CREATEUSER
        {
            get
            {
                return _CREATEUSER;
            }
            set
            {
                OnCREATEUSERChanging(value);
                ReportPropertyChanging("CREATEUSER");
                _CREATEUSER = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CREATEUSER");
                OnCREATEUSERChanged();
            }
        }
        private global::System.String _CREATEUSER;
        partial void OnCREATEUSERChanging(global::System.String value);
        partial void OnCREATEUSERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UPDATEDATE
        {
            get
            {
                return _UPDATEDATE;
            }
            set
            {
                OnUPDATEDATEChanging(value);
                ReportPropertyChanging("UPDATEDATE");
                _UPDATEDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATEDATE");
                OnUPDATEDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _UPDATEDATE;
        partial void OnUPDATEDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnUPDATEDATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UPDATEUSER
        {
            get
            {
                return _UPDATEUSER;
            }
            set
            {
                OnUPDATEUSERChanging(value);
                ReportPropertyChanging("UPDATEUSER");
                _UPDATEUSER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UPDATEUSER");
                OnUPDATEUSERChanged();
            }
        }
        private global::System.String _UPDATEUSER;
        partial void OnUPDATEUSERChanging(global::System.String value);
        partial void OnUPDATEUSERChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AdminModel", "FK_tb_GroupMapping_tb_UserGroups", "tb_GroupMapping")]
        public EntityCollection<tb_GroupMapping> tb_GroupMapping
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_GroupMapping>("AdminModel.FK_tb_GroupMapping_tb_UserGroups", "tb_GroupMapping");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_GroupMapping>("AdminModel.FK_tb_GroupMapping_tb_UserGroups", "tb_GroupMapping", value);
                }
            }
        }

        #endregion
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="AdminModel", Name="sp_ADM010_UserMaintenance_SearchAll_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class sp_ADM010_UserMaintenance_SearchAll_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sp_ADM010_UserMaintenance_SearchAll_Result object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="loginTypeName">Initial value of the LoginTypeName property.</param>
        /// <param name="createUser">Initial value of the CreateUser property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        public static sp_ADM010_UserMaintenance_SearchAll_Result Createsp_ADM010_UserMaintenance_SearchAll_Result(global::System.String userID, global::System.String firstName, global::System.String loginTypeName, global::System.String createUser, global::System.DateTime createDate)
        {
            sp_ADM010_UserMaintenance_SearchAll_Result sp_ADM010_UserMaintenance_SearchAll_Result = new sp_ADM010_UserMaintenance_SearchAll_Result();
            sp_ADM010_UserMaintenance_SearchAll_Result.UserID = userID;
            sp_ADM010_UserMaintenance_SearchAll_Result.FirstName = firstName;
            sp_ADM010_UserMaintenance_SearchAll_Result.LoginTypeName = loginTypeName;
            sp_ADM010_UserMaintenance_SearchAll_Result.CreateUser = createUser;
            sp_ADM010_UserMaintenance_SearchAll_Result.CreateDate = createDate;
            return sp_ADM010_UserMaintenance_SearchAll_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.String _UserID;
        partial void OnUserIDChanging(global::System.String value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telephone
        {
            get
            {
                return _Telephone;
            }
            set
            {
                OnTelephoneChanging(value);
                ReportPropertyChanging("Telephone");
                _Telephone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telephone");
                OnTelephoneChanged();
            }
        }
        private global::System.String _Telephone;
        partial void OnTelephoneChanging(global::System.String value);
        partial void OnTelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mobile
        {
            get
            {
                return _Mobile;
            }
            set
            {
                OnMobileChanging(value);
                ReportPropertyChanging("Mobile");
                _Mobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mobile");
                OnMobileChanged();
            }
        }
        private global::System.String _Mobile;
        partial void OnMobileChanging(global::System.String value);
        partial void OnMobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LoginType
        {
            get
            {
                return _LoginType;
            }
            set
            {
                OnLoginTypeChanging(value);
                ReportPropertyChanging("LoginType");
                _LoginType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoginType");
                OnLoginTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _LoginType;
        partial void OnLoginTypeChanging(Nullable<global::System.Int32> value);
        partial void OnLoginTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoginTypeName
        {
            get
            {
                return _LoginTypeName;
            }
            set
            {
                OnLoginTypeNameChanging(value);
                ReportPropertyChanging("LoginTypeName");
                _LoginTypeName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LoginTypeName");
                OnLoginTypeNameChanged();
            }
        }
        private global::System.String _LoginTypeName;
        partial void OnLoginTypeNameChanging(global::System.String value);
        partial void OnLoginTypeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DomainIPAddress
        {
            get
            {
                return _DomainIPAddress;
            }
            set
            {
                OnDomainIPAddressChanging(value);
                ReportPropertyChanging("DomainIPAddress");
                _DomainIPAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DomainIPAddress");
                OnDomainIPAddressChanged();
            }
        }
        private global::System.String _DomainIPAddress;
        partial void OnDomainIPAddressChanging(global::System.String value);
        partial void OnDomainIPAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DomainName
        {
            get
            {
                return _DomainName;
            }
            set
            {
                OnDomainNameChanging(value);
                ReportPropertyChanging("DomainName");
                _DomainName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DomainName");
                OnDomainNameChanged();
            }
        }
        private global::System.String _DomainName;
        partial void OnDomainNameChanging(global::System.String value);
        partial void OnDomainNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WarehouseCode
        {
            get
            {
                return _WarehouseCode;
            }
            set
            {
                OnWarehouseCodeChanging(value);
                ReportPropertyChanging("WarehouseCode");
                _WarehouseCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WarehouseCode");
                OnWarehouseCodeChanged();
            }
        }
        private global::System.String _WarehouseCode;
        partial void OnWarehouseCodeChanging(global::System.String value);
        partial void OnWarehouseCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WarehouseName
        {
            get
            {
                return _WarehouseName;
            }
            set
            {
                OnWarehouseNameChanging(value);
                ReportPropertyChanging("WarehouseName");
                _WarehouseName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WarehouseName");
                OnWarehouseNameChanged();
            }
        }
        private global::System.String _WarehouseName;
        partial void OnWarehouseNameChanging(global::System.String value);
        partial void OnWarehouseNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OwnerCode
        {
            get
            {
                return _OwnerCode;
            }
            set
            {
                OnOwnerCodeChanging(value);
                ReportPropertyChanging("OwnerCode");
                _OwnerCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OwnerCode");
                OnOwnerCodeChanged();
            }
        }
        private global::System.String _OwnerCode;
        partial void OnOwnerCodeChanging(global::System.String value);
        partial void OnOwnerCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OwnerID
        {
            get
            {
                return _OwnerID;
            }
            set
            {
                OnOwnerIDChanging(value);
                ReportPropertyChanging("OwnerID");
                _OwnerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OwnerID");
                OnOwnerIDChanged();
            }
        }
        private Nullable<global::System.Int32> _OwnerID;
        partial void OnOwnerIDChanging(Nullable<global::System.Int32> value);
        partial void OnOwnerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OwnerName
        {
            get
            {
                return _OwnerName;
            }
            set
            {
                OnOwnerNameChanging(value);
                ReportPropertyChanging("OwnerName");
                _OwnerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OwnerName");
                OnOwnerNameChanged();
            }
        }
        private global::System.String _OwnerName;
        partial void OnOwnerNameChanging(global::System.String value);
        partial void OnOwnerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreateUser
        {
            get
            {
                return _CreateUser;
            }
            set
            {
                OnCreateUserChanging(value);
                ReportPropertyChanging("CreateUser");
                _CreateUser = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreateUser");
                OnCreateUserChanged();
            }
        }
        private global::System.String _CreateUser;
        partial void OnCreateUserChanging(global::System.String value);
        partial void OnCreateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdateUser
        {
            get
            {
                return _UpdateUser;
            }
            set
            {
                OnUpdateUserChanging(value);
                ReportPropertyChanging("UpdateUser");
                _UpdateUser = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdateUser");
                OnUpdateUserChanged();
            }
        }
        private global::System.String _UpdateUser;
        partial void OnUpdateUserChanging(global::System.String value);
        partial void OnUpdateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateDate
        {
            get
            {
                return _UpdateDate;
            }
            set
            {
                OnUpdateDateChanging(value);
                ReportPropertyChanging("UpdateDate");
                _UpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateDate");
                OnUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateDate;
        partial void OnUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateDateChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="AdminModel", Name="sp_ADM020_LoadGroup_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class sp_ADM020_LoadGroup_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sp_ADM020_LoadGroup_Result object.
        /// </summary>
        /// <param name="groupID">Initial value of the GroupID property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        /// <param name="createUser">Initial value of the CreateUser property.</param>
        public static sp_ADM020_LoadGroup_Result Createsp_ADM020_LoadGroup_Result(global::System.Decimal groupID, global::System.DateTime createDate, global::System.String createUser)
        {
            sp_ADM020_LoadGroup_Result sp_ADM020_LoadGroup_Result = new sp_ADM020_LoadGroup_Result();
            sp_ADM020_LoadGroup_Result.GroupID = groupID;
            sp_ADM020_LoadGroup_Result.CreateDate = createDate;
            sp_ADM020_LoadGroup_Result.CreateUser = createUser;
            return sp_ADM020_LoadGroup_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                OnGroupIDChanging(value);
                ReportPropertyChanging("GroupID");
                _GroupID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupID");
                OnGroupIDChanged();
            }
        }
        private global::System.Decimal _GroupID;
        partial void OnGroupIDChanging(global::System.Decimal value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GroupName
        {
            get
            {
                return _GroupName;
            }
            set
            {
                OnGroupNameChanging(value);
                ReportPropertyChanging("GroupName");
                _GroupName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GroupName");
                OnGroupNameChanged();
            }
        }
        private global::System.String _GroupName;
        partial void OnGroupNameChanging(global::System.String value);
        partial void OnGroupNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreateUser
        {
            get
            {
                return _CreateUser;
            }
            set
            {
                OnCreateUserChanging(value);
                ReportPropertyChanging("CreateUser");
                _CreateUser = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreateUser");
                OnCreateUserChanged();
            }
        }
        private global::System.String _CreateUser;
        partial void OnCreateUserChanging(global::System.String value);
        partial void OnCreateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateDate
        {
            get
            {
                return _UpdateDate;
            }
            set
            {
                OnUpdateDateChanging(value);
                ReportPropertyChanging("UpdateDate");
                _UpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateDate");
                OnUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateDate;
        partial void OnUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdateUser
        {
            get
            {
                return _UpdateUser;
            }
            set
            {
                OnUpdateUserChanging(value);
                ReportPropertyChanging("UpdateUser");
                _UpdateUser = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdateUser");
                OnUpdateUserChanged();
            }
        }
        private global::System.String _UpdateUser;
        partial void OnUpdateUserChanging(global::System.String value);
        partial void OnUpdateUserChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="AdminModel", Name="sp_ADM020_LoadUserByGroup_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class sp_ADM020_LoadUserByGroup_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sp_ADM020_LoadUserByGroup_Result object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        public static sp_ADM020_LoadUserByGroup_Result Createsp_ADM020_LoadUserByGroup_Result(global::System.String userID, global::System.String firstName)
        {
            sp_ADM020_LoadUserByGroup_Result sp_ADM020_LoadUserByGroup_Result = new sp_ADM020_LoadUserByGroup_Result();
            sp_ADM020_LoadUserByGroup_Result.UserID = userID;
            sp_ADM020_LoadUserByGroup_Result.FirstName = firstName;
            return sp_ADM020_LoadUserByGroup_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.String _UserID;
        partial void OnUserIDChanging(global::System.String value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telephone
        {
            get
            {
                return _Telephone;
            }
            set
            {
                OnTelephoneChanging(value);
                ReportPropertyChanging("Telephone");
                _Telephone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telephone");
                OnTelephoneChanged();
            }
        }
        private global::System.String _Telephone;
        partial void OnTelephoneChanging(global::System.String value);
        partial void OnTelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mobile
        {
            get
            {
                return _Mobile;
            }
            set
            {
                OnMobileChanging(value);
                ReportPropertyChanging("Mobile");
                _Mobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mobile");
                OnMobileChanged();
            }
        }
        private global::System.String _Mobile;
        partial void OnMobileChanging(global::System.String value);
        partial void OnMobileChanged();

        #endregion
    }

    #endregion
    
}
