//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace CSI.Business.DataObjects
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class O_D_TransitModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new O_D_TransitModelContainer object using the connection string found in the 'O_D_TransitModelContainer' section of the application configuration file.
        /// </summary>
        public O_D_TransitModelContainer() : base("name=O_D_TransitModelContainer", "O_D_TransitModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new O_D_TransitModelContainer object.
        /// </summary>
        public O_D_TransitModelContainer(string connectionString) : base(connectionString, "O_D_TransitModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new O_D_TransitModelContainer object.
        /// </summary>
        public O_D_TransitModelContainer(EntityConnection connection) : base(connection, "O_D_TransitModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbt_TransitConfirmed> tbt_TransitConfirmed
        {
            get
            {
                if ((_tbt_TransitConfirmed == null))
                {
                    _tbt_TransitConfirmed = base.CreateObjectSet<tbt_TransitConfirmed>("tbt_TransitConfirmed");
                }
                return _tbt_TransitConfirmed;
            }
        }
        private ObjectSet<tbt_TransitConfirmed> _tbt_TransitConfirmed;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbt_TransitInstructionItems> tbt_TransitInstructionItems
        {
            get
            {
                if ((_tbt_TransitInstructionItems == null))
                {
                    _tbt_TransitInstructionItems = base.CreateObjectSet<tbt_TransitInstructionItems>("tbt_TransitInstructionItems");
                }
                return _tbt_TransitInstructionItems;
            }
        }
        private ObjectSet<tbt_TransitInstructionItems> _tbt_TransitInstructionItems;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbt_TransitConfirmed EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbt_TransitConfirmed(tbt_TransitConfirmed tbt_TransitConfirmed)
        {
            base.AddObject("tbt_TransitConfirmed", tbt_TransitConfirmed);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbt_TransitInstructionItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbt_TransitInstructionItems(tbt_TransitInstructionItems tbt_TransitInstructionItems)
        {
            base.AddObject("tbt_TransitInstructionItems", tbt_TransitInstructionItems);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="locationID">No Metadata Documentation available.</param>
        public ObjectResult<sp_DSRS010_ConfirmProductStoring_LoadStockByLocation_Result> sp_DSRS010_ConfirmProductStoring_LoadStockByLocation(Nullable<global::System.Int32> locationID)
        {
            ObjectParameter locationIDParameter;
            if (locationID.HasValue)
            {
                locationIDParameter = new ObjectParameter("LocationID", locationID);
            }
            else
            {
                locationIDParameter = new ObjectParameter("LocationID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<sp_DSRS010_ConfirmProductStoring_LoadStockByLocation_Result>("sp_DSRS010_ConfirmProductStoring_LoadStockByLocation", locationIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="ownerID">No Metadata Documentation available.</param>
        /// <param name="warehouseID">No Metadata Documentation available.</param>
        /// <param name="receivingNo">No Metadata Documentation available.</param>
        /// <param name="lineNo">No Metadata Documentation available.</param>
        /// <param name="supplierID">No Metadata Documentation available.</param>
        /// <param name="showConfirm">No Metadata Documentation available.</param>
        /// <param name="isAfterMarket">No Metadata Documentation available.</param>
        /// <param name="transitDateFrom">No Metadata Documentation available.</param>
        /// <param name="transitDateTo">No Metadata Documentation available.</param>
        /// <param name="isPackingMaterial">No Metadata Documentation available.</param>
        /// <param name="isPart">No Metadata Documentation available.</param>
        public ObjectResult<sp_DSRS010_ConfirmProductStoring_SearchAll_Result> sp_DSRS010_ConfirmProductStoring_SearchAll(Nullable<global::System.Int32> ownerID, Nullable<global::System.Int32> warehouseID, global::System.String receivingNo, Nullable<global::System.Int32> lineNo, Nullable<global::System.Int32> supplierID, Nullable<global::System.Int32> showConfirm, Nullable<global::System.Int32> isAfterMarket, Nullable<global::System.DateTime> transitDateFrom, Nullable<global::System.DateTime> transitDateTo, Nullable<global::System.Int32> isPackingMaterial, Nullable<global::System.Int32> isPart)
        {
            ObjectParameter ownerIDParameter;
            if (ownerID.HasValue)
            {
                ownerIDParameter = new ObjectParameter("OwnerID", ownerID);
            }
            else
            {
                ownerIDParameter = new ObjectParameter("OwnerID", typeof(global::System.Int32));
            }
    
            ObjectParameter warehouseIDParameter;
            if (warehouseID.HasValue)
            {
                warehouseIDParameter = new ObjectParameter("WarehouseID", warehouseID);
            }
            else
            {
                warehouseIDParameter = new ObjectParameter("WarehouseID", typeof(global::System.Int32));
            }
    
            ObjectParameter receivingNoParameter;
            if (receivingNo != null)
            {
                receivingNoParameter = new ObjectParameter("ReceivingNo", receivingNo);
            }
            else
            {
                receivingNoParameter = new ObjectParameter("ReceivingNo", typeof(global::System.String));
            }
    
            ObjectParameter lineNoParameter;
            if (lineNo.HasValue)
            {
                lineNoParameter = new ObjectParameter("LineNo", lineNo);
            }
            else
            {
                lineNoParameter = new ObjectParameter("LineNo", typeof(global::System.Int32));
            }
    
            ObjectParameter supplierIDParameter;
            if (supplierID.HasValue)
            {
                supplierIDParameter = new ObjectParameter("SupplierID", supplierID);
            }
            else
            {
                supplierIDParameter = new ObjectParameter("SupplierID", typeof(global::System.Int32));
            }
    
            ObjectParameter showConfirmParameter;
            if (showConfirm.HasValue)
            {
                showConfirmParameter = new ObjectParameter("ShowConfirm", showConfirm);
            }
            else
            {
                showConfirmParameter = new ObjectParameter("ShowConfirm", typeof(global::System.Int32));
            }
    
            ObjectParameter isAfterMarketParameter;
            if (isAfterMarket.HasValue)
            {
                isAfterMarketParameter = new ObjectParameter("isAfterMarket", isAfterMarket);
            }
            else
            {
                isAfterMarketParameter = new ObjectParameter("isAfterMarket", typeof(global::System.Int32));
            }
    
            ObjectParameter transitDateFromParameter;
            if (transitDateFrom.HasValue)
            {
                transitDateFromParameter = new ObjectParameter("TransitDateFrom", transitDateFrom);
            }
            else
            {
                transitDateFromParameter = new ObjectParameter("TransitDateFrom", typeof(global::System.DateTime));
            }
    
            ObjectParameter transitDateToParameter;
            if (transitDateTo.HasValue)
            {
                transitDateToParameter = new ObjectParameter("TransitDateTo", transitDateTo);
            }
            else
            {
                transitDateToParameter = new ObjectParameter("TransitDateTo", typeof(global::System.DateTime));
            }
    
            ObjectParameter isPackingMaterialParameter;
            if (isPackingMaterial.HasValue)
            {
                isPackingMaterialParameter = new ObjectParameter("isPackingMaterial", isPackingMaterial);
            }
            else
            {
                isPackingMaterialParameter = new ObjectParameter("isPackingMaterial", typeof(global::System.Int32));
            }
    
            ObjectParameter isPartParameter;
            if (isPart.HasValue)
            {
                isPartParameter = new ObjectParameter("isPart", isPart);
            }
            else
            {
                isPartParameter = new ObjectParameter("isPart", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<sp_DSRS010_ConfirmProductStoring_SearchAll_Result>("sp_DSRS010_ConfirmProductStoring_SearchAll", ownerIDParameter, warehouseIDParameter, receivingNoParameter, lineNoParameter, supplierIDParameter, showConfirmParameter, isAfterMarketParameter, transitDateFromParameter, transitDateToParameter, isPackingMaterialParameter, isPartParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="ownerID">No Metadata Documentation available.</param>
        /// <param name="receivingNo">No Metadata Documentation available.</param>
        /// <param name="installment">No Metadata Documentation available.</param>
        /// <param name="lineNo">No Metadata Documentation available.</param>
        /// <param name="receiveSeq">No Metadata Documentation available.</param>
        public ObjectResult<sp_DSRS010_ConfirmProductStoring_LoadTransitConfirm_Result> sp_DSRS010_ConfirmProductStoring_LoadTransitConfirm(Nullable<global::System.Int32> ownerID, global::System.String receivingNo, Nullable<global::System.Int32> installment, Nullable<global::System.Int32> lineNo, Nullable<global::System.Int32> receiveSeq)
        {
            ObjectParameter ownerIDParameter;
            if (ownerID.HasValue)
            {
                ownerIDParameter = new ObjectParameter("OwnerID", ownerID);
            }
            else
            {
                ownerIDParameter = new ObjectParameter("OwnerID", typeof(global::System.Int32));
            }
    
            ObjectParameter receivingNoParameter;
            if (receivingNo != null)
            {
                receivingNoParameter = new ObjectParameter("ReceivingNo", receivingNo);
            }
            else
            {
                receivingNoParameter = new ObjectParameter("ReceivingNo", typeof(global::System.String));
            }
    
            ObjectParameter installmentParameter;
            if (installment.HasValue)
            {
                installmentParameter = new ObjectParameter("Installment", installment);
            }
            else
            {
                installmentParameter = new ObjectParameter("Installment", typeof(global::System.Int32));
            }
    
            ObjectParameter lineNoParameter;
            if (lineNo.HasValue)
            {
                lineNoParameter = new ObjectParameter("LineNo", lineNo);
            }
            else
            {
                lineNoParameter = new ObjectParameter("LineNo", typeof(global::System.Int32));
            }
    
            ObjectParameter receiveSeqParameter;
            if (receiveSeq.HasValue)
            {
                receiveSeqParameter = new ObjectParameter("ReceiveSeq", receiveSeq);
            }
            else
            {
                receiveSeqParameter = new ObjectParameter("ReceiveSeq", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<sp_DSRS010_ConfirmProductStoring_LoadTransitConfirm_Result>("sp_DSRS010_ConfirmProductStoring_LoadTransitConfirm", ownerIDParameter, receivingNoParameter, installmentParameter, lineNoParameter, receiveSeqParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="receivingNo">No Metadata Documentation available.</param>
        /// <param name="lineNo">No Metadata Documentation available.</param>
        /// <param name="receiveSeq">No Metadata Documentation available.</param>
        public ObjectResult<sp_DSRS010_ConfirmProductStoring_LoadSuggest_Result> sp_DSRS010_ConfirmProductStoring_LoadSuggest(global::System.String receivingNo, Nullable<global::System.Int32> lineNo, Nullable<global::System.Int32> receiveSeq)
        {
            ObjectParameter receivingNoParameter;
            if (receivingNo != null)
            {
                receivingNoParameter = new ObjectParameter("ReceivingNo", receivingNo);
            }
            else
            {
                receivingNoParameter = new ObjectParameter("ReceivingNo", typeof(global::System.String));
            }
    
            ObjectParameter lineNoParameter;
            if (lineNo.HasValue)
            {
                lineNoParameter = new ObjectParameter("LineNo", lineNo);
            }
            else
            {
                lineNoParameter = new ObjectParameter("LineNo", typeof(global::System.Int32));
            }
    
            ObjectParameter receiveSeqParameter;
            if (receiveSeq.HasValue)
            {
                receiveSeqParameter = new ObjectParameter("ReceiveSeq", receiveSeq);
            }
            else
            {
                receiveSeqParameter = new ObjectParameter("ReceiveSeq", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<sp_DSRS010_ConfirmProductStoring_LoadSuggest_Result>("sp_DSRS010_ConfirmProductStoring_LoadSuggest", receivingNoParameter, lineNoParameter, receiveSeqParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="O_D_TransitModel", Name="tbt_TransitConfirmed")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbt_TransitConfirmed : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbt_TransitConfirmed object.
        /// </summary>
        /// <param name="ownerID">Initial value of the OwnerID property.</param>
        /// <param name="receivingNo">Initial value of the ReceivingNo property.</param>
        /// <param name="installment">Initial value of the Installment property.</param>
        /// <param name="lineNo">Initial value of the LineNo property.</param>
        /// <param name="receiveSeq">Initial value of the ReceiveSeq property.</param>
        /// <param name="transitSeq">Initial value of the TransitSeq property.</param>
        /// <param name="locationID">Initial value of the LocationID property.</param>
        /// <param name="transitQty">Initial value of the TransitQty property.</param>
        /// <param name="confirmFlag">Initial value of the ConfirmFlag property.</param>
        public static tbt_TransitConfirmed Createtbt_TransitConfirmed(global::System.Int32 ownerID, global::System.String receivingNo, global::System.Int32 installment, global::System.Int32 lineNo, global::System.Int32 receiveSeq, global::System.Int32 transitSeq, global::System.Int32 locationID, global::System.Decimal transitQty, global::System.Boolean confirmFlag)
        {
            tbt_TransitConfirmed tbt_TransitConfirmed = new tbt_TransitConfirmed();
            tbt_TransitConfirmed.OwnerID = ownerID;
            tbt_TransitConfirmed.ReceivingNo = receivingNo;
            tbt_TransitConfirmed.Installment = installment;
            tbt_TransitConfirmed.LineNo = lineNo;
            tbt_TransitConfirmed.ReceiveSeq = receiveSeq;
            tbt_TransitConfirmed.TransitSeq = transitSeq;
            tbt_TransitConfirmed.LocationID = locationID;
            tbt_TransitConfirmed.TransitQty = transitQty;
            tbt_TransitConfirmed.ConfirmFlag = confirmFlag;
            return tbt_TransitConfirmed;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OwnerID
        {
            get
            {
                return _OwnerID;
            }
            set
            {
                OnOwnerIDChanging(value);
                ReportPropertyChanging("OwnerID");
                _OwnerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OwnerID");
                OnOwnerIDChanged();
            }
        }
        private global::System.Int32 _OwnerID;
        partial void OnOwnerIDChanging(global::System.Int32 value);
        partial void OnOwnerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ReceivingNo
        {
            get
            {
                return _ReceivingNo;
            }
            set
            {
                if (_ReceivingNo != value)
                {
                    OnReceivingNoChanging(value);
                    ReportPropertyChanging("ReceivingNo");
                    _ReceivingNo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ReceivingNo");
                    OnReceivingNoChanged();
                }
            }
        }
        private global::System.String _ReceivingNo;
        partial void OnReceivingNoChanging(global::System.String value);
        partial void OnReceivingNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Installment
        {
            get
            {
                return _Installment;
            }
            set
            {
                if (_Installment != value)
                {
                    OnInstallmentChanging(value);
                    ReportPropertyChanging("Installment");
                    _Installment = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Installment");
                    OnInstallmentChanged();
                }
            }
        }
        private global::System.Int32 _Installment;
        partial void OnInstallmentChanging(global::System.Int32 value);
        partial void OnInstallmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LineNo
        {
            get
            {
                return _LineNo;
            }
            set
            {
                if (_LineNo != value)
                {
                    OnLineNoChanging(value);
                    ReportPropertyChanging("LineNo");
                    _LineNo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LineNo");
                    OnLineNoChanged();
                }
            }
        }
        private global::System.Int32 _LineNo;
        partial void OnLineNoChanging(global::System.Int32 value);
        partial void OnLineNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReceiveSeq
        {
            get
            {
                return _ReceiveSeq;
            }
            set
            {
                if (_ReceiveSeq != value)
                {
                    OnReceiveSeqChanging(value);
                    ReportPropertyChanging("ReceiveSeq");
                    _ReceiveSeq = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ReceiveSeq");
                    OnReceiveSeqChanged();
                }
            }
        }
        private global::System.Int32 _ReceiveSeq;
        partial void OnReceiveSeqChanging(global::System.Int32 value);
        partial void OnReceiveSeqChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TransitSeq
        {
            get
            {
                return _TransitSeq;
            }
            set
            {
                if (_TransitSeq != value)
                {
                    OnTransitSeqChanging(value);
                    ReportPropertyChanging("TransitSeq");
                    _TransitSeq = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TransitSeq");
                    OnTransitSeqChanged();
                }
            }
        }
        private global::System.Int32 _TransitSeq;
        partial void OnTransitSeqChanging(global::System.Int32 value);
        partial void OnTransitSeqChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LocationID
        {
            get
            {
                return _LocationID;
            }
            set
            {
                OnLocationIDChanging(value);
                ReportPropertyChanging("LocationID");
                _LocationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocationID");
                OnLocationIDChanged();
            }
        }
        private global::System.Int32 _LocationID;
        partial void OnLocationIDChanging(global::System.Int32 value);
        partial void OnLocationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TransitQty
        {
            get
            {
                return _TransitQty;
            }
            set
            {
                OnTransitQtyChanging(value);
                ReportPropertyChanging("TransitQty");
                _TransitQty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TransitQty");
                OnTransitQtyChanged();
            }
        }
        private global::System.Decimal _TransitQty;
        partial void OnTransitQtyChanging(global::System.Decimal value);
        partial void OnTransitQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ConfirmFlag
        {
            get
            {
                return _ConfirmFlag;
            }
            set
            {
                OnConfirmFlagChanging(value);
                ReportPropertyChanging("ConfirmFlag");
                _ConfirmFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConfirmFlag");
                OnConfirmFlagChanged();
            }
        }
        private global::System.Boolean _ConfirmFlag;
        partial void OnConfirmFlagChanging(global::System.Boolean value);
        partial void OnConfirmFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdate
        {
            get
            {
                return _LastUpdate;
            }
            set
            {
                OnLastUpdateChanging(value);
                ReportPropertyChanging("LastUpdate");
                _LastUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdate");
                OnLastUpdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdate;
        partial void OnLastUpdateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> StockActualQty
        {
            get
            {
                return _StockActualQty;
            }
            set
            {
                OnStockActualQtyChanging(value);
                ReportPropertyChanging("StockActualQty");
                _StockActualQty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StockActualQty");
                OnStockActualQtyChanged();
            }
        }
        private Nullable<global::System.Decimal> _StockActualQty;
        partial void OnStockActualQtyChanging(Nullable<global::System.Decimal> value);
        partial void OnStockActualQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreateUser
        {
            get
            {
                return _CreateUser;
            }
            set
            {
                OnCreateUserChanging(value);
                ReportPropertyChanging("CreateUser");
                _CreateUser = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreateUser");
                OnCreateUserChanged();
            }
        }
        private global::System.String _CreateUser;
        partial void OnCreateUserChanging(global::System.String value);
        partial void OnCreateUserChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="O_D_TransitModel", Name="tbt_TransitInstructionItems")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbt_TransitInstructionItems : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbt_TransitInstructionItems object.
        /// </summary>
        /// <param name="ownerID">Initial value of the OwnerID property.</param>
        /// <param name="receivingNo">Initial value of the ReceivingNo property.</param>
        /// <param name="installment">Initial value of the Installment property.</param>
        /// <param name="lineNo">Initial value of the LineNo property.</param>
        /// <param name="palletNo">Initial value of the PalletNo property.</param>
        /// <param name="productID">Initial value of the ProductID property.</param>
        /// <param name="productConditionID">Initial value of the ProductConditionID property.</param>
        /// <param name="transitInstructQty">Initial value of the TransitInstructQty property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        /// <param name="createUser">Initial value of the CreateUser property.</param>
        public static tbt_TransitInstructionItems Createtbt_TransitInstructionItems(global::System.Int32 ownerID, global::System.String receivingNo, global::System.Int32 installment, global::System.Int32 lineNo, global::System.String palletNo, global::System.Int32 productID, global::System.Int32 productConditionID, global::System.Decimal transitInstructQty, global::System.DateTime createDate, global::System.String createUser)
        {
            tbt_TransitInstructionItems tbt_TransitInstructionItems = new tbt_TransitInstructionItems();
            tbt_TransitInstructionItems.OwnerID = ownerID;
            tbt_TransitInstructionItems.ReceivingNo = receivingNo;
            tbt_TransitInstructionItems.Installment = installment;
            tbt_TransitInstructionItems.LineNo = lineNo;
            tbt_TransitInstructionItems.PalletNo = palletNo;
            tbt_TransitInstructionItems.ProductID = productID;
            tbt_TransitInstructionItems.ProductConditionID = productConditionID;
            tbt_TransitInstructionItems.TransitInstructQty = transitInstructQty;
            tbt_TransitInstructionItems.CreateDate = createDate;
            tbt_TransitInstructionItems.CreateUser = createUser;
            return tbt_TransitInstructionItems;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OwnerID
        {
            get
            {
                return _OwnerID;
            }
            set
            {
                OnOwnerIDChanging(value);
                ReportPropertyChanging("OwnerID");
                _OwnerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OwnerID");
                OnOwnerIDChanged();
            }
        }
        private global::System.Int32 _OwnerID;
        partial void OnOwnerIDChanging(global::System.Int32 value);
        partial void OnOwnerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ReceivingNo
        {
            get
            {
                return _ReceivingNo;
            }
            set
            {
                if (_ReceivingNo != value)
                {
                    OnReceivingNoChanging(value);
                    ReportPropertyChanging("ReceivingNo");
                    _ReceivingNo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ReceivingNo");
                    OnReceivingNoChanged();
                }
            }
        }
        private global::System.String _ReceivingNo;
        partial void OnReceivingNoChanging(global::System.String value);
        partial void OnReceivingNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Installment
        {
            get
            {
                return _Installment;
            }
            set
            {
                if (_Installment != value)
                {
                    OnInstallmentChanging(value);
                    ReportPropertyChanging("Installment");
                    _Installment = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Installment");
                    OnInstallmentChanged();
                }
            }
        }
        private global::System.Int32 _Installment;
        partial void OnInstallmentChanging(global::System.Int32 value);
        partial void OnInstallmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LineNo
        {
            get
            {
                return _LineNo;
            }
            set
            {
                if (_LineNo != value)
                {
                    OnLineNoChanging(value);
                    ReportPropertyChanging("LineNo");
                    _LineNo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LineNo");
                    OnLineNoChanged();
                }
            }
        }
        private global::System.Int32 _LineNo;
        partial void OnLineNoChanging(global::System.Int32 value);
        partial void OnLineNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PalletNo
        {
            get
            {
                return _PalletNo;
            }
            set
            {
                OnPalletNoChanging(value);
                ReportPropertyChanging("PalletNo");
                _PalletNo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PalletNo");
                OnPalletNoChanged();
            }
        }
        private global::System.String _PalletNo;
        partial void OnPalletNoChanging(global::System.String value);
        partial void OnPalletNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                OnProductIDChanging(value);
                ReportPropertyChanging("ProductID");
                _ProductID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductID");
                OnProductIDChanged();
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductConditionID
        {
            get
            {
                return _ProductConditionID;
            }
            set
            {
                OnProductConditionIDChanging(value);
                ReportPropertyChanging("ProductConditionID");
                _ProductConditionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductConditionID");
                OnProductConditionIDChanged();
            }
        }
        private global::System.Int32 _ProductConditionID;
        partial void OnProductConditionIDChanging(global::System.Int32 value);
        partial void OnProductConditionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TransitInstructQty
        {
            get
            {
                return _TransitInstructQty;
            }
            set
            {
                OnTransitInstructQtyChanging(value);
                ReportPropertyChanging("TransitInstructQty");
                _TransitInstructQty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TransitInstructQty");
                OnTransitInstructQtyChanged();
            }
        }
        private global::System.Decimal _TransitInstructQty;
        partial void OnTransitInstructQtyChanging(global::System.Decimal value);
        partial void OnTransitInstructQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ConfirmTransitDraftTime
        {
            get
            {
                return _ConfirmTransitDraftTime;
            }
            set
            {
                OnConfirmTransitDraftTimeChanging(value);
                ReportPropertyChanging("ConfirmTransitDraftTime");
                _ConfirmTransitDraftTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConfirmTransitDraftTime");
                OnConfirmTransitDraftTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ConfirmTransitDraftTime;
        partial void OnConfirmTransitDraftTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnConfirmTransitDraftTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ConfirmTransitDraftNo
        {
            get
            {
                return _ConfirmTransitDraftNo;
            }
            set
            {
                OnConfirmTransitDraftNoChanging(value);
                ReportPropertyChanging("ConfirmTransitDraftNo");
                _ConfirmTransitDraftNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ConfirmTransitDraftNo");
                OnConfirmTransitDraftNoChanged();
            }
        }
        private global::System.String _ConfirmTransitDraftNo;
        partial void OnConfirmTransitDraftNoChanging(global::System.String value);
        partial void OnConfirmTransitDraftNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreateUser
        {
            get
            {
                return _CreateUser;
            }
            set
            {
                OnCreateUserChanging(value);
                ReportPropertyChanging("CreateUser");
                _CreateUser = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreateUser");
                OnCreateUserChanged();
            }
        }
        private global::System.String _CreateUser;
        partial void OnCreateUserChanging(global::System.String value);
        partial void OnCreateUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateDate
        {
            get
            {
                return _UpdateDate;
            }
            set
            {
                OnUpdateDateChanging(value);
                ReportPropertyChanging("UpdateDate");
                _UpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateDate");
                OnUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateDate;
        partial void OnUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdateUser
        {
            get
            {
                return _UpdateUser;
            }
            set
            {
                OnUpdateUserChanging(value);
                ReportPropertyChanging("UpdateUser");
                _UpdateUser = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdateUser");
                OnUpdateUserChanged();
            }
        }
        private global::System.String _UpdateUser;
        partial void OnUpdateUserChanging(global::System.String value);
        partial void OnUpdateUserChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="O_D_TransitModel", Name="sp_DSRS010_ConfirmProductStoring_LoadStockByLocation_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class sp_DSRS010_ConfirmProductStoring_LoadStockByLocation_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sp_DSRS010_ConfirmProductStoring_LoadStockByLocation_Result object.
        /// </summary>
        /// <param name="transitSeq">Initial value of the TransitSeq property.</param>
        /// <param name="locationID">Initial value of the LocationID property.</param>
        /// <param name="currentCapacity">Initial value of the CurrentCapacity property.</param>
        /// <param name="unitCode">Initial value of the UnitCode property.</param>
        public static sp_DSRS010_ConfirmProductStoring_LoadStockByLocation_Result Createsp_DSRS010_ConfirmProductStoring_LoadStockByLocation_Result(global::System.Int32 transitSeq, global::System.Int32 locationID, global::System.Decimal currentCapacity, global::System.String unitCode)
        {
            sp_DSRS010_ConfirmProductStoring_LoadStockByLocation_Result sp_DSRS010_ConfirmProductStoring_LoadStockByLocation_Result = new sp_DSRS010_ConfirmProductStoring_LoadStockByLocation_Result();
            sp_DSRS010_ConfirmProductStoring_LoadStockByLocation_Result.TransitSeq = transitSeq;
            sp_DSRS010_ConfirmProductStoring_LoadStockByLocation_Result.LocationID = locationID;
            sp_DSRS010_ConfirmProductStoring_LoadStockByLocation_Result.CurrentCapacity = currentCapacity;
            sp_DSRS010_ConfirmProductStoring_LoadStockByLocation_Result.UnitCode = unitCode;
            return sp_DSRS010_ConfirmProductStoring_LoadStockByLocation_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TransitSeq
        {
            get
            {
                return _TransitSeq;
            }
            set
            {
                OnTransitSeqChanging(value);
                ReportPropertyChanging("TransitSeq");
                _TransitSeq = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TransitSeq");
                OnTransitSeqChanged();
            }
        }
        private global::System.Int32 _TransitSeq;
        partial void OnTransitSeqChanging(global::System.Int32 value);
        partial void OnTransitSeqChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LocationID
        {
            get
            {
                return _LocationID;
            }
            set
            {
                OnLocationIDChanging(value);
                ReportPropertyChanging("LocationID");
                _LocationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocationID");
                OnLocationIDChanged();
            }
        }
        private global::System.Int32 _LocationID;
        partial void OnLocationIDChanging(global::System.Int32 value);
        partial void OnLocationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalCapacity
        {
            get
            {
                return _TotalCapacity;
            }
            set
            {
                OnTotalCapacityChanging(value);
                ReportPropertyChanging("TotalCapacity");
                _TotalCapacity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalCapacity");
                OnTotalCapacityChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalCapacity;
        partial void OnTotalCapacityChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalCapacityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CurrentCapacity
        {
            get
            {
                return _CurrentCapacity;
            }
            set
            {
                OnCurrentCapacityChanging(value);
                ReportPropertyChanging("CurrentCapacity");
                _CurrentCapacity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentCapacity");
                OnCurrentCapacityChanged();
            }
        }
        private global::System.Decimal _CurrentCapacity;
        partial void OnCurrentCapacityChanging(global::System.Decimal value);
        partial void OnCurrentCapacityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> StockActualQty
        {
            get
            {
                return _StockActualQty;
            }
            set
            {
                OnStockActualQtyChanging(value);
                ReportPropertyChanging("StockActualQty");
                _StockActualQty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StockActualQty");
                OnStockActualQtyChanged();
            }
        }
        private Nullable<global::System.Decimal> _StockActualQty;
        partial void OnStockActualQtyChanging(Nullable<global::System.Decimal> value);
        partial void OnStockActualQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> FullCapacityFlag
        {
            get
            {
                return _FullCapacityFlag;
            }
            set
            {
                OnFullCapacityFlagChanging(value);
                ReportPropertyChanging("FullCapacityFlag");
                _FullCapacityFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FullCapacityFlag");
                OnFullCapacityFlagChanged();
            }
        }
        private Nullable<global::System.Boolean> _FullCapacityFlag;
        partial void OnFullCapacityFlagChanging(Nullable<global::System.Boolean> value);
        partial void OnFullCapacityFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UnitCode
        {
            get
            {
                return _UnitCode;
            }
            set
            {
                OnUnitCodeChanging(value);
                ReportPropertyChanging("UnitCode");
                _UnitCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UnitCode");
                OnUnitCodeChanged();
            }
        }
        private global::System.String _UnitCode;
        partial void OnUnitCodeChanging(global::System.String value);
        partial void OnUnitCodeChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="O_D_TransitModel", Name="sp_DSRS010_ConfirmProductStoring_LoadSuggest_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class sp_DSRS010_ConfirmProductStoring_LoadSuggest_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sp_DSRS010_ConfirmProductStoring_LoadSuggest_Result object.
        /// </summary>
        /// <param name="transitSeq">Initial value of the TransitSeq property.</param>
        public static sp_DSRS010_ConfirmProductStoring_LoadSuggest_Result Createsp_DSRS010_ConfirmProductStoring_LoadSuggest_Result(global::System.Int32 transitSeq)
        {
            sp_DSRS010_ConfirmProductStoring_LoadSuggest_Result sp_DSRS010_ConfirmProductStoring_LoadSuggest_Result = new sp_DSRS010_ConfirmProductStoring_LoadSuggest_Result();
            sp_DSRS010_ConfirmProductStoring_LoadSuggest_Result.TransitSeq = transitSeq;
            return sp_DSRS010_ConfirmProductStoring_LoadSuggest_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TransitSeq
        {
            get
            {
                return _TransitSeq;
            }
            set
            {
                OnTransitSeqChanging(value);
                ReportPropertyChanging("TransitSeq");
                _TransitSeq = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TransitSeq");
                OnTransitSeqChanged();
            }
        }
        private global::System.Int32 _TransitSeq;
        partial void OnTransitSeqChanging(global::System.Int32 value);
        partial void OnTransitSeqChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LocationID
        {
            get
            {
                return _LocationID;
            }
            set
            {
                OnLocationIDChanging(value);
                ReportPropertyChanging("LocationID");
                _LocationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocationID");
                OnLocationIDChanged();
            }
        }
        private Nullable<global::System.Int32> _LocationID;
        partial void OnLocationIDChanging(Nullable<global::System.Int32> value);
        partial void OnLocationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalCapacity
        {
            get
            {
                return _TotalCapacity;
            }
            set
            {
                OnTotalCapacityChanging(value);
                ReportPropertyChanging("TotalCapacity");
                _TotalCapacity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalCapacity");
                OnTotalCapacityChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalCapacity;
        partial void OnTotalCapacityChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalCapacityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CurrentCapacity
        {
            get
            {
                return _CurrentCapacity;
            }
            set
            {
                OnCurrentCapacityChanging(value);
                ReportPropertyChanging("CurrentCapacity");
                _CurrentCapacity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentCapacity");
                OnCurrentCapacityChanged();
            }
        }
        private Nullable<global::System.Decimal> _CurrentCapacity;
        partial void OnCurrentCapacityChanging(Nullable<global::System.Decimal> value);
        partial void OnCurrentCapacityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> StockActualQty
        {
            get
            {
                return _StockActualQty;
            }
            set
            {
                OnStockActualQtyChanging(value);
                ReportPropertyChanging("StockActualQty");
                _StockActualQty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StockActualQty");
                OnStockActualQtyChanged();
            }
        }
        private Nullable<global::System.Decimal> _StockActualQty;
        partial void OnStockActualQtyChanging(Nullable<global::System.Decimal> value);
        partial void OnStockActualQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> FullCapacityFlag
        {
            get
            {
                return _FullCapacityFlag;
            }
            set
            {
                OnFullCapacityFlagChanging(value);
                ReportPropertyChanging("FullCapacityFlag");
                _FullCapacityFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FullCapacityFlag");
                OnFullCapacityFlagChanged();
            }
        }
        private Nullable<global::System.Boolean> _FullCapacityFlag;
        partial void OnFullCapacityFlagChanging(Nullable<global::System.Boolean> value);
        partial void OnFullCapacityFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UnitCode
        {
            get
            {
                return _UnitCode;
            }
            set
            {
                OnUnitCodeChanging(value);
                ReportPropertyChanging("UnitCode");
                _UnitCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UnitCode");
                OnUnitCodeChanged();
            }
        }
        private global::System.String _UnitCode;
        partial void OnUnitCodeChanging(global::System.String value);
        partial void OnUnitCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LocationTypeID
        {
            get
            {
                return _LocationTypeID;
            }
            set
            {
                OnLocationTypeIDChanging(value);
                ReportPropertyChanging("LocationTypeID");
                _LocationTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocationTypeID");
                OnLocationTypeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _LocationTypeID;
        partial void OnLocationTypeIDChanging(Nullable<global::System.Int32> value);
        partial void OnLocationTypeIDChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="O_D_TransitModel", Name="sp_DSRS010_ConfirmProductStoring_LoadTransitConfirm_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class sp_DSRS010_ConfirmProductStoring_LoadTransitConfirm_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sp_DSRS010_ConfirmProductStoring_LoadTransitConfirm_Result object.
        /// </summary>
        /// <param name="transitSeq">Initial value of the TransitSeq property.</param>
        /// <param name="unitCode">Initial value of the UnitCode property.</param>
        public static sp_DSRS010_ConfirmProductStoring_LoadTransitConfirm_Result Createsp_DSRS010_ConfirmProductStoring_LoadTransitConfirm_Result(global::System.Int32 transitSeq, global::System.String unitCode)
        {
            sp_DSRS010_ConfirmProductStoring_LoadTransitConfirm_Result sp_DSRS010_ConfirmProductStoring_LoadTransitConfirm_Result = new sp_DSRS010_ConfirmProductStoring_LoadTransitConfirm_Result();
            sp_DSRS010_ConfirmProductStoring_LoadTransitConfirm_Result.TransitSeq = transitSeq;
            sp_DSRS010_ConfirmProductStoring_LoadTransitConfirm_Result.UnitCode = unitCode;
            return sp_DSRS010_ConfirmProductStoring_LoadTransitConfirm_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TransitSeq
        {
            get
            {
                return _TransitSeq;
            }
            set
            {
                OnTransitSeqChanging(value);
                ReportPropertyChanging("TransitSeq");
                _TransitSeq = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TransitSeq");
                OnTransitSeqChanged();
            }
        }
        private global::System.Int32 _TransitSeq;
        partial void OnTransitSeqChanging(global::System.Int32 value);
        partial void OnTransitSeqChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LocationID
        {
            get
            {
                return _LocationID;
            }
            set
            {
                OnLocationIDChanging(value);
                ReportPropertyChanging("LocationID");
                _LocationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocationID");
                OnLocationIDChanged();
            }
        }
        private Nullable<global::System.Int32> _LocationID;
        partial void OnLocationIDChanging(Nullable<global::System.Int32> value);
        partial void OnLocationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalCapacity
        {
            get
            {
                return _TotalCapacity;
            }
            set
            {
                OnTotalCapacityChanging(value);
                ReportPropertyChanging("TotalCapacity");
                _TotalCapacity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalCapacity");
                OnTotalCapacityChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalCapacity;
        partial void OnTotalCapacityChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalCapacityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CurrentCapacity
        {
            get
            {
                return _CurrentCapacity;
            }
            set
            {
                OnCurrentCapacityChanging(value);
                ReportPropertyChanging("CurrentCapacity");
                _CurrentCapacity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentCapacity");
                OnCurrentCapacityChanged();
            }
        }
        private Nullable<global::System.Decimal> _CurrentCapacity;
        partial void OnCurrentCapacityChanging(Nullable<global::System.Decimal> value);
        partial void OnCurrentCapacityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> StockActualQty
        {
            get
            {
                return _StockActualQty;
            }
            set
            {
                OnStockActualQtyChanging(value);
                ReportPropertyChanging("StockActualQty");
                _StockActualQty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StockActualQty");
                OnStockActualQtyChanged();
            }
        }
        private Nullable<global::System.Decimal> _StockActualQty;
        partial void OnStockActualQtyChanging(Nullable<global::System.Decimal> value);
        partial void OnStockActualQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> FullCapacityFlag
        {
            get
            {
                return _FullCapacityFlag;
            }
            set
            {
                OnFullCapacityFlagChanging(value);
                ReportPropertyChanging("FullCapacityFlag");
                _FullCapacityFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FullCapacityFlag");
                OnFullCapacityFlagChanged();
            }
        }
        private Nullable<global::System.Boolean> _FullCapacityFlag;
        partial void OnFullCapacityFlagChanging(Nullable<global::System.Boolean> value);
        partial void OnFullCapacityFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UnitCode
        {
            get
            {
                return _UnitCode;
            }
            set
            {
                OnUnitCodeChanging(value);
                ReportPropertyChanging("UnitCode");
                _UnitCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UnitCode");
                OnUnitCodeChanged();
            }
        }
        private global::System.String _UnitCode;
        partial void OnUnitCodeChanging(global::System.String value);
        partial void OnUnitCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LocationTypeID
        {
            get
            {
                return _LocationTypeID;
            }
            set
            {
                OnLocationTypeIDChanging(value);
                ReportPropertyChanging("LocationTypeID");
                _LocationTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocationTypeID");
                OnLocationTypeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _LocationTypeID;
        partial void OnLocationTypeIDChanging(Nullable<global::System.Int32> value);
        partial void OnLocationTypeIDChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="O_D_TransitModel", Name="sp_DSRS010_ConfirmProductStoring_SearchAll_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class sp_DSRS010_ConfirmProductStoring_SearchAll_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sp_DSRS010_ConfirmProductStoring_SearchAll_Result object.
        /// </summary>
        /// <param name="ownerID">Initial value of the OwnerID property.</param>
        /// <param name="receivingNo">Initial value of the ReceivingNo property.</param>
        /// <param name="productID">Initial value of the ProductID property.</param>
        /// <param name="productConditionID">Initial value of the ProductConditionID property.</param>
        /// <param name="transitStatus">Initial value of the TransitStatus property.</param>
        /// <param name="transitCompleteFlag">Initial value of the TransitCompleteFlag property.</param>
        /// <param name="warehouseID">Initial value of the WarehouseID property.</param>
        /// <param name="receiveSeq">Initial value of the ReceiveSeq property.</param>
        /// <param name="statusID">Initial value of the StatusID property.</param>
        /// <param name="installment">Initial value of the Installment property.</param>
        /// <param name="lineNo">Initial value of the LineNo property.</param>
        /// <param name="unitCode">Initial value of the UnitCode property.</param>
        public static sp_DSRS010_ConfirmProductStoring_SearchAll_Result Createsp_DSRS010_ConfirmProductStoring_SearchAll_Result(global::System.Int32 ownerID, global::System.String receivingNo, global::System.Int32 productID, global::System.Int32 productConditionID, global::System.String transitStatus, global::System.Boolean transitCompleteFlag, global::System.Int32 warehouseID, global::System.Int32 receiveSeq, global::System.Int32 statusID, global::System.Int32 installment, global::System.Int32 lineNo, global::System.String unitCode)
        {
            sp_DSRS010_ConfirmProductStoring_SearchAll_Result sp_DSRS010_ConfirmProductStoring_SearchAll_Result = new sp_DSRS010_ConfirmProductStoring_SearchAll_Result();
            sp_DSRS010_ConfirmProductStoring_SearchAll_Result.OwnerID = ownerID;
            sp_DSRS010_ConfirmProductStoring_SearchAll_Result.ReceivingNo = receivingNo;
            sp_DSRS010_ConfirmProductStoring_SearchAll_Result.ProductID = productID;
            sp_DSRS010_ConfirmProductStoring_SearchAll_Result.ProductConditionID = productConditionID;
            sp_DSRS010_ConfirmProductStoring_SearchAll_Result.TransitStatus = transitStatus;
            sp_DSRS010_ConfirmProductStoring_SearchAll_Result.TransitCompleteFlag = transitCompleteFlag;
            sp_DSRS010_ConfirmProductStoring_SearchAll_Result.WarehouseID = warehouseID;
            sp_DSRS010_ConfirmProductStoring_SearchAll_Result.ReceiveSeq = receiveSeq;
            sp_DSRS010_ConfirmProductStoring_SearchAll_Result.StatusID = statusID;
            sp_DSRS010_ConfirmProductStoring_SearchAll_Result.Installment = installment;
            sp_DSRS010_ConfirmProductStoring_SearchAll_Result.LineNo = lineNo;
            sp_DSRS010_ConfirmProductStoring_SearchAll_Result.UnitCode = unitCode;
            return sp_DSRS010_ConfirmProductStoring_SearchAll_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OwnerID
        {
            get
            {
                return _OwnerID;
            }
            set
            {
                OnOwnerIDChanging(value);
                ReportPropertyChanging("OwnerID");
                _OwnerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OwnerID");
                OnOwnerIDChanged();
            }
        }
        private global::System.Int32 _OwnerID;
        partial void OnOwnerIDChanging(global::System.Int32 value);
        partial void OnOwnerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Select
        {
            get
            {
                return _Select;
            }
            set
            {
                OnSelectChanging(value);
                ReportPropertyChanging("Select");
                _Select = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Select");
                OnSelectChanged();
            }
        }
        private Nullable<global::System.Boolean> _Select;
        partial void OnSelectChanging(Nullable<global::System.Boolean> value);
        partial void OnSelectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ReceivingNo
        {
            get
            {
                return _ReceivingNo;
            }
            set
            {
                OnReceivingNoChanging(value);
                ReportPropertyChanging("ReceivingNo");
                _ReceivingNo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ReceivingNo");
                OnReceivingNoChanged();
            }
        }
        private global::System.String _ReceivingNo;
        partial void OnReceivingNoChanging(global::System.String value);
        partial void OnReceivingNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SortedLineNo
        {
            get
            {
                return _SortedLineNo;
            }
            set
            {
                OnSortedLineNoChanging(value);
                ReportPropertyChanging("SortedLineNo");
                _SortedLineNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SortedLineNo");
                OnSortedLineNoChanged();
            }
        }
        private Nullable<global::System.Int32> _SortedLineNo;
        partial void OnSortedLineNoChanging(Nullable<global::System.Int32> value);
        partial void OnSortedLineNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                OnProductIDChanging(value);
                ReportPropertyChanging("ProductID");
                _ProductID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductID");
                OnProductIDChanged();
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductConditionID
        {
            get
            {
                return _ProductConditionID;
            }
            set
            {
                OnProductConditionIDChanging(value);
                ReportPropertyChanging("ProductConditionID");
                _ProductConditionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductConditionID");
                OnProductConditionIDChanged();
            }
        }
        private global::System.Int32 _ProductConditionID;
        partial void OnProductConditionIDChanging(global::System.Int32 value);
        partial void OnProductConditionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Qty
        {
            get
            {
                return _Qty;
            }
            set
            {
                OnQtyChanging(value);
                ReportPropertyChanging("Qty");
                _Qty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Qty");
                OnQtyChanged();
            }
        }
        private Nullable<global::System.Decimal> _Qty;
        partial void OnQtyChanging(Nullable<global::System.Decimal> value);
        partial void OnQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ReceiveQty
        {
            get
            {
                return _ReceiveQty;
            }
            set
            {
                OnReceiveQtyChanging(value);
                ReportPropertyChanging("ReceiveQty");
                _ReceiveQty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReceiveQty");
                OnReceiveQtyChanged();
            }
        }
        private Nullable<global::System.Decimal> _ReceiveQty;
        partial void OnReceiveQtyChanging(Nullable<global::System.Decimal> value);
        partial void OnReceiveQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TransitQty
        {
            get
            {
                return _TransitQty;
            }
            set
            {
                OnTransitQtyChanging(value);
                ReportPropertyChanging("TransitQty");
                _TransitQty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TransitQty");
                OnTransitQtyChanged();
            }
        }
        private Nullable<global::System.Decimal> _TransitQty;
        partial void OnTransitQtyChanging(Nullable<global::System.Decimal> value);
        partial void OnTransitQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TransitStatus
        {
            get
            {
                return _TransitStatus;
            }
            set
            {
                OnTransitStatusChanging(value);
                ReportPropertyChanging("TransitStatus");
                _TransitStatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TransitStatus");
                OnTransitStatusChanged();
            }
        }
        private global::System.String _TransitStatus;
        partial void OnTransitStatusChanging(global::System.String value);
        partial void OnTransitStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean TransitCompleteFlag
        {
            get
            {
                return _TransitCompleteFlag;
            }
            set
            {
                OnTransitCompleteFlagChanging(value);
                ReportPropertyChanging("TransitCompleteFlag");
                _TransitCompleteFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TransitCompleteFlag");
                OnTransitCompleteFlagChanged();
            }
        }
        private global::System.Boolean _TransitCompleteFlag;
        partial void OnTransitCompleteFlagChanging(global::System.Boolean value);
        partial void OnTransitCompleteFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LocationID
        {
            get
            {
                return _LocationID;
            }
            set
            {
                OnLocationIDChanging(value);
                ReportPropertyChanging("LocationID");
                _LocationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocationID");
                OnLocationIDChanged();
            }
        }
        private Nullable<global::System.Int32> _LocationID;
        partial void OnLocationIDChanging(Nullable<global::System.Int32> value);
        partial void OnLocationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TransitDate
        {
            get
            {
                return _TransitDate;
            }
            set
            {
                OnTransitDateChanging(value);
                ReportPropertyChanging("TransitDate");
                _TransitDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TransitDate");
                OnTransitDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _TransitDate;
        partial void OnTransitDateChanging(Nullable<global::System.DateTime> value);
        partial void OnTransitDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WarehouseID
        {
            get
            {
                return _WarehouseID;
            }
            set
            {
                OnWarehouseIDChanging(value);
                ReportPropertyChanging("WarehouseID");
                _WarehouseID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WarehouseID");
                OnWarehouseIDChanged();
            }
        }
        private global::System.Int32 _WarehouseID;
        partial void OnWarehouseIDChanging(global::System.Int32 value);
        partial void OnWarehouseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReceiveSeq
        {
            get
            {
                return _ReceiveSeq;
            }
            set
            {
                OnReceiveSeqChanging(value);
                ReportPropertyChanging("ReceiveSeq");
                _ReceiveSeq = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReceiveSeq");
                OnReceiveSeqChanged();
            }
        }
        private global::System.Int32 _ReceiveSeq;
        partial void OnReceiveSeqChanging(global::System.Int32 value);
        partial void OnReceiveSeqChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TransitSeq
        {
            get
            {
                return _TransitSeq;
            }
            set
            {
                OnTransitSeqChanging(value);
                ReportPropertyChanging("TransitSeq");
                _TransitSeq = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TransitSeq");
                OnTransitSeqChanged();
            }
        }
        private Nullable<global::System.Int32> _TransitSeq;
        partial void OnTransitSeqChanging(Nullable<global::System.Int32> value);
        partial void OnTransitSeqChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StatusID
        {
            get
            {
                return _StatusID;
            }
            set
            {
                OnStatusIDChanging(value);
                ReportPropertyChanging("StatusID");
                _StatusID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusID");
                OnStatusIDChanged();
            }
        }
        private global::System.Int32 _StatusID;
        partial void OnStatusIDChanging(global::System.Int32 value);
        partial void OnStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Installment
        {
            get
            {
                return _Installment;
            }
            set
            {
                OnInstallmentChanging(value);
                ReportPropertyChanging("Installment");
                _Installment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Installment");
                OnInstallmentChanged();
            }
        }
        private global::System.Int32 _Installment;
        partial void OnInstallmentChanging(global::System.Int32 value);
        partial void OnInstallmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LineNo
        {
            get
            {
                return _LineNo;
            }
            set
            {
                OnLineNoChanging(value);
                ReportPropertyChanging("LineNo");
                _LineNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LineNo");
                OnLineNoChanged();
            }
        }
        private global::System.Int32 _LineNo;
        partial void OnLineNoChanging(global::System.Int32 value);
        partial void OnLineNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PalletNo
        {
            get
            {
                return _PalletNo;
            }
            set
            {
                OnPalletNoChanging(value);
                ReportPropertyChanging("PalletNo");
                _PalletNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PalletNo");
                OnPalletNoChanged();
            }
        }
        private global::System.String _PalletNo;
        partial void OnPalletNoChanging(global::System.String value);
        partial void OnPalletNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LotNo
        {
            get
            {
                return _LotNo;
            }
            set
            {
                OnLotNoChanging(value);
                ReportPropertyChanging("LotNo");
                _LotNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LotNo");
                OnLotNoChanged();
            }
        }
        private global::System.String _LotNo;
        partial void OnLotNoChanging(global::System.String value);
        partial void OnLotNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> FullFlag
        {
            get
            {
                return _FullFlag;
            }
            set
            {
                OnFullFlagChanging(value);
                ReportPropertyChanging("FullFlag");
                _FullFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FullFlag");
                OnFullFlagChanged();
            }
        }
        private Nullable<global::System.Boolean> _FullFlag;
        partial void OnFullFlagChanging(Nullable<global::System.Boolean> value);
        partial void OnFullFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AllStatus
        {
            get
            {
                return _AllStatus;
            }
            set
            {
                OnAllStatusChanging(value);
                ReportPropertyChanging("AllStatus");
                _AllStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllStatus");
                OnAllStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _AllStatus;
        partial void OnAllStatusChanging(Nullable<global::System.Int32> value);
        partial void OnAllStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UnitCode
        {
            get
            {
                return _UnitCode;
            }
            set
            {
                OnUnitCodeChanging(value);
                ReportPropertyChanging("UnitCode");
                _UnitCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UnitCode");
                OnUnitCodeChanged();
            }
        }
        private global::System.String _UnitCode;
        partial void OnUnitCodeChanging(global::System.String value);
        partial void OnUnitCodeChanged();

        #endregion

    }

    #endregion

    
}
